version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: ticketflow_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/var/www
    networks:
      - laravel

  db:
    image: postgres:16
    container_name: ticketflow_db
    restart: always
    environment:
      POSTGRES_DB: db_kp_ticketflow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  pgdata: